server:
  port: 3333

spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://localhost:8081"

logging:
  level:
    com.tbs.notificationservice: DEBUG